.DEFAULT_GOAL := help

.PHONY: clean clean-static clean-pyc clean-full \
	help production-requirements requirements \
	quality test validate isort black format migrate celery runserver static

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## Display this help message
	@echo "Please use \`make <target>\` where <target> is one of"
	@grep '^[a-zA-Z]' $(MAKEFILE_LIST) | sort | awk -F ':.*?## ' 'NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean-pyc: ## Remove Python file artifacts
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +

clean-static: ## Remove generated static files
	rm -rf .staticfiles/*

clean: clean-static clean-pyc ## Remove build, python cache and statifiles artifacts

clean-full: clean ## Remove pyc, static files and venv
	rm -rf .venv venv

requirements: ## Install Python and npm requirements for local development
	pip install -r requirements-dev.txt

production-requirements: ## Install Python requirements for production
	pip install -r requirements.txt



test: ## Run tests and generate coverage report
	python manage.py check


unittests:## Run integration tests
	python manage.py test --keepdb --noinput --failfast -b -v 1

integration_tests:## Run integration tests
	python manage.py test --keepdb --noinput --failfast -b -v 1 tests/

validate: quality test ## Run tests and quality checks


black: ## Apply black formatting to python files
	black *

format: isort black ## Apply isort and black formatting to python files

migrate: ## Apply database migrations
	python manage.py migrate --noinput


start: ## Run Django server
	python manage.py runserver

static: ## Gather all static assets for production
	python manage.py collectstatic -v 0 --noinput
redis-start:
	docker-compose -f .\redis-docker.yaml up -d

redis-stop:
	docker-compose -f .\redis-docker.yaml down -

db-start:
	docker-compose -f .\postgres-docker.yaml up -d

db-stop:
	docker-compose -f .\postgres-docker.yaml down -d