version: 'latest'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=zZuWp1Kz8F3o1vvW5NpbjBkAEIjv79tLUpxV3
      - POSTGRES_DB=vidyalu_db
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local