# Isort configuration
[tool.isort]
line_length = 150
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
lines_after_imports = 2
combine_as_imports = true
default_section = "THIRDPARTY"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party Modules"


[tool.black]
target_version = ['py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.vscode
  |\.staticfiles
  |\.eggs
  |\.hg
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.venv
  |venv
  |node_modules
  |_build
  |buck-out
  |build
  |dist
  |media
  |provisioner
  |templates
)/
'''
